name: jokes_about_chuck
description: Random jokes about Chuck Norris.

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.0-beta4
  dio_cookie_manager: ^2.0.0-beta1
  flutter_launcher_icons: ^0.9.0
  flutter_svg: ^0.21.0-nullsafety.0
  image_picker: ^0.7.4
  intl: ^0.17.0
  pedantic: ^1.9.2
  pretty_dio_logger: ^1.1.1
  provider: ^5.0.0-nullsafety.5
  shared_preferences: ^2.0.5
  test: ^1.16.0-nullsafety.5
  url_launcher: ^6.0.3
  animated_text_kit: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
